name: speedtest

# 触发条件
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["gradNode"]
    types: [completed]
#  schedule:
# 表达式生成  https://crontab.guru/ 
#    - cron: '10 0,6,12,18 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: 安装Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: 加载缓存
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
# 安装依赖和工具
    - name: 安装依赖
      run: |
        pip install -r ./utils/requirements.txt
    - name: 安装Country.mmdb - ip库
      run: |        
        wget -O Country.mmdb https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb
    - name: 安装订阅转换工具-subconverter
      run: |
        wget -O subconverter.tar.gz https://raw.githubusercontent.com/rxsweet/all/main/githubTools/subconverter.tar.gz
        tar -zxvf subconverter.tar.gz -C ./
        chmod +x ./subconverter/subconverter && nohup ./subconverter/subconverter >./subconverter.log 2>&1 &
    - name: 安装测速工具-clash
      run: |
        wget -O clash-linuxamd64.gz https://raw.githubusercontent.com/rxsweet/all/main/githubTools/clash-linux-amd64-v1.11.4.gz
        gunzip clash-linuxamd64.gz
        chmod +x ./clash-linux-amd64 && ./clash-linuxamd64 & 
# 执行任务            
    - name: 执行任务 - 1.speedtest
      run:
       sudo chmod 777 clash-linuxamd64 && python ./utils/speedtest/main.py
       
    - name: 执行任务 - 2.convert to sub 
      run:
       python ./utils/speedtest/convert2sub/convert2sub.py
       
    - name: 执行任务 - 3.update readme
      run:
       python ./utils/readme_update.py   
# 提交           
    - name: 提交更改
      run: |                 
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin main
        git add ./sub
        git add README.md
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') check done "
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
        branch: main
