name: mail_cloud.py
on:
  workflow_dispatch:
  schedule:
    #- cron: 0 4,10,16,22 * * * #北京时间：每6小时
    - cron: 0 10,23 * * * #北京时间：早7点，晚6点
permissions: write-all
jobs:
  main:
    runs-on: ubuntu-latest
    #env:
      #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #DDAL_EMAIL: ${{ secrets.DDAL_EMAIL }}
      #DDAL_PASSWORD: ${{ secrets.DDAL_PASSWORD }}
    steps:
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai' 
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Prepare #禁用了chrome
        run: pip install requests beautifulsoup4 ruamel.yaml json5
      - name: 执行任务 -1.Run get_trial.py
        run: cd ./utils/mailCloud/ && python get_trial.py
      - name: 执行任务 -2.copy to ./sub/
        run: |
          cp ./utils/mailCloud/trial ./sub/v.txt
          cp ./utils/mailCloud/trial.yaml ./sub/v.yaml
      - name: 执行任务 - 3.log
        run:
         python ./utils/subConvert/log.py 'mailCloud sub'  
      - name: Commit
        id: commit
        continue-on-error: true
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S') mailCloud update done"
          #git commit -m "${{ github.workflow }} https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          git pull --rebase
      - uses: ad-m/github-push-action@master
        if: ${{ steps.commit.outcome == 'success' }}
      #- name: Run get_trial_update_url.py
        #run: python get_trial_update_url.py
      - name: Pushes to proxies
        uses: rxsweet/copy_file_to_another_repo_action@main
        env:
         API_TOKEN_GITHUB: ghp_xxx
        with:
          source_file: 'sub/'
          destination_repo: 'rxsweet/proxies'
          user_email: 'actions@github.com'
          user_name: 'GitHub Actions'
          commit_message: 'mailCloud update done'
