name: fetch clash speedtest

# 触发条件
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["fetch Share Sub"]
    types: [completed]
#  schedule:
# 表达式生成  https://crontab.guru/ 
#    - cron: '10 0,6,12,18 * * *'

jobs:
  deploy:
# 基本系统配置
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: 安装Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: 加载缓存
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
# 安装依赖和工具
    - name: 安装依赖
      run: |
        pip install -r ./utils/requirements.txt
    - name: 安装Country.mmdb - ip库
      run: |        
        python ./utils/subConvert/ip_update.py
    - name: 安装订阅转换工具-subconverter
      run: |
        wget -O subconverter.tar.gz https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz
        tar -zxvf subconverter.tar.gz -C ./
        chmod +x ./subconverter/subconverter && nohup ./subconverter/subconverter >./subconverter.log 2>&1 &
    - name: 安装测速工具-clash
      run: |
        wget -O clash-linuxamd64.gz https://github.com/Dreamacro/clash/releases/download/v1.11.8/clash-linux-amd64-v1.11.8.gz
        gunzip clash-linuxamd64.gz
        chmod +x ./clash-linux-amd64 && ./clash-linuxamd64 & 
# 执行任务            
    - name: 执行任务 - 1.set config.yaml 
      run:
       python ./utils/fetchShareSub/speedtest/clash_set_config.py
       
    - name: 执行任务 - 2.convert to sub 
      run:
       sudo chmod 777 clash-linuxamd64 && python ./utils/clashspeedtest/main.py
# 提交           
    - name: 提交更改
      run: |                 
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin main
        git add ./sub
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') check done "
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
        branch: main
         
    - name: Pushes to useProxies
      uses: rxsweet/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ghp_xx
      with:
        source_file: 'sub/'
        destination_repo: 'rxsweet/useProxies'
        user_email: 'sweetrx@pm.me'
        user_name: 'rxsweet'
        commit_message: "fetchShare clash speedtest"
