name: liteSpeedtest

# 触发条件
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["crawlNode"]
    types: [completed]
#  schedule:
# 表达式生成  https://crontab.guru/ 
#    - cron: '10 0,6,12,18 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: 安装Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: 加载缓存
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 安装依赖
      run: |
        pip install -r ./utils/requirements.txt
    - name: 安装订阅转换工具-subconverter
      run: |
        wget -O subconverter.tar.gz https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz
        tar -zxvf subconverter.tar.gz -C ./
        chmod +x ./subconverter/subconverter && nohup ./subconverter/subconverter >./subconverter.log 2>&1 &
        
    - name: 安装测速工具并运行liteSpeedtest --- out.json & speedtest.log
      run: |
        sudo sh ./utils/litespeedtest/speedtest.sh
    - name: 转换 --- literx & literxClash.yml
      run: |
        python ./utils/litespeedtest/output.py
        python ./utils/litespeedtest/lite2sub/convert2sub.py
#    - name: out.json & speedtest.log --- rm & mv
#      run: |       
#        rm ./sub/checkBakup/out.json
#        rm ./sub/checkBakup/speedtest.log
#        mv ./out.json ./sub/checkBakup/out.json
#        mv ./speedtest.log ./sub/checkBakup/speedtest.log
    - name: commit
      run: |                 
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin main
        git add ./sub
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') litespeedtest done"
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
        # github_token: ${{ secrets.TOKEN }}
        branch: main
